title: "Andy Clynes (CakeIsGoodForYou) â€¢ GitHub Examples"
theme: jekyll-theme-minimal

# Optional: Add your info
author: Andy Clynes
email: cakeisgoodforyou123@gmail.com

# Custom styling
header_pages:
  - index.md

# Remove default blue color
sass:
  style: compressed